### PR TITLE
Demo

### PR DESCRIPTION
**Pull request by baloyan**
- Add HTTP/HTTPS server

- Modified CMakeList.txt in order to build Boost Lib, which is required by HTTP/HTTPS server 

-  Add Travis CI (.travis.yml file) in CacheCash

-  Add test_cachecash.sh bach script, currently it just builds project, it does not run testcases.

- Add demo website

### CODE REVIEW

**Comment by SantiagoTorres** [comment]
Sorry to jump in but:

1. Why would you require boost for a simple https server, can' you just python -m "SimpleHTTPSServer" or use the builtin from openssl
2. Even worse, you have *another* webserver from django in there
3. Even worse, you have yet another node webserver
4. Even worse you committed all the *.pyc files (which are binaries), and all the _pycache_ folders
5. Even worse, you committed all the node_modules files. You were expected to write a package.json file in the root of your node application.

I honestly don't think anyone can review a 271k addition-long PR.

**Comment by baloyan** [comment]
This PR has to be fixed before PR

**Comment by lukpueh** [comment]
So here is how I see this:

- The Django web-app part is fine, since it serves your CacheCash JavaScript client and does user handling. 
- You also need a C http(s) API, for your Content Provider and your Caches (idk if you really need boost for this, and/or a lot of third-party boilerplate HTTP code in your repo)
- I don't see why you would need a JS web-server. You don't have any serving JavaScript component. Your JavaScript CacheCash client is (as the name suggests) a client running in a browser, i.e. it just needs ways of calling HTTP(s) APIs, something that browsers can usually provide.

**Comment by JustinCappos** [comment]
The demo application and the rest of the system need to be clearly
differentiated.  Perhaps having separate repos for them makes sense?

**Comment by baloyan** [comment]
You are right, for Content Provider and Caches we need API, this is why we
use Simple-Web-Server C++/C++11 API library
https://github.com/eidheim/Simple-Web-Server, which provides everything
what we need, and this library requires Boost C++ lib.

Currently we do not have any serving JavaScript component, but later we are
going have it.
Whole Client side of CacheCash should be implemented in JavaScript.

**Comment by JustinCappos** [comment]
I think we've discussed this before, but I'll say it here too.  I think we
will end up with both a JS and a C/C++ implementation of the client.

We already have the client code in C/C++ and while it isn't that useful for
most deployments, it should be helpful for benchmarking...

**Pull request closed without merging**
